/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema;

import entidades.Cliente;
import entidades.ClienteService;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CadastroCliente extends javax.swing.JFrame {

    private ClienteService service = new ClienteService();
    private Cliente cliente = new Cliente();

    /**
     * Creates new form Pessoa
     */
    public CadastroCliente() {
        initComponents();
        AberturaDeTelaNovo();
    }

    public CadastroCliente(Cliente cliente) {
        initComponents();
        AberturaDeTelaEdicao();
        carregarCliente(cliente);
    }

    private void carregarCliente(Cliente cliente) {
        this.cliente = cliente;
        LblCodigoCliente.setText(String.valueOf(cliente.getId()));
        TxtNome.setText(cliente.getNome());
        TxtCPF.setText(cliente.getCpf());
        TxtRG.setText(cliente.getRg());
        CbxSituacao.setSelected(cliente.getSituacao());
        TxtCidade.setText(cliente.getCidade());
        TxtEndereco.setText(cliente.getEndereco());
        TxtBairro.setText(cliente.getEnderecoBairro());
        TxtNumero.setText(String.valueOf(cliente.getNumeroEndereco()));
        TxtCEP.setText(String.valueOf(cliente.getCep()));
        TxtEstado.setText(cliente.getEstado());
        TxtDataNascimento.setText(String.valueOf(cliente.getDataNascimento()));
        TxtObservacao.setText(cliente.getObservacao());
    }

    private void AberturaDeTelaNovo() {

        // Configura o título da janela
        setTitle("Cadastro de Clientes");

        // Obtém o tamanho da tela
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        // Centraliza a janela no centro da tela
        setLocationRelativeTo(null);

        // Mostra a janela
        setVisible(true);

        BtnExcluir.setVisible(false);
        BtnExcluir.setEnabled(false);

        //Abrir janela com foco
        TxtNome.requestFocusInWindow();

        //Fechar apenar este formulario
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void AberturaDeTelaEdicao() {

        // Configura o título da janela
        setTitle("Cadastro de Clientes");

        // Obtém o tamanho da tela
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        // Centraliza a janela no centro da tela
        setLocationRelativeTo(null);

        // Mostra a janela
        setVisible(true);

        BtnExcluir.setVisible(true);
        BtnExcluir.setEnabled(true);

        //Abrir janela com foco
        TxtNome.requestFocusInWindow();

        //Fechar apenar este formulario
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCEP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnRetornar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtDataNascimento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LblCodigoCliente = new javax.swing.JLabel();
        CbxSituacao = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        TxtEstado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtObservacao = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        TxtRG = new javax.swing.JTextField();
        BtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome Completo:");

        TxtNome.setName("EdtNome"); // NOI18N
        TxtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNomeKeyPressed(evt);
            }
        });

        jLabel2.setText("CPF:");

        TxtCPF.setName("EdtCPF"); // NOI18N
        TxtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCPFKeyPressed(evt);
            }
        });

        jLabel3.setText("CEP:");

        TxtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCidadeKeyPressed(evt);
            }
        });

        jLabel4.setText("Cidade:");

        TxtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtBairroKeyPressed(evt);
            }
        });

        jLabel5.setText("Endereço:");

        TxtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtEnderecoKeyPressed(evt);
            }
        });

        jLabel6.setText("Bairro:");

        TxtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCEPKeyPressed(evt);
            }
        });

        jLabel7.setText("Nº:");

        TxtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNumeroKeyPressed(evt);
            }
        });

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/disk.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalvarMouseClicked(evt);
            }
        });
        BtnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSalvarKeyPressed(evt);
            }
        });

        BtnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow_redo.png"))); // NOI18N
        BtnRetornar.setText("Retornar");
        BtnRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRetornarMouseClicked(evt);
            }
        });

        jLabel8.setText("Data Nascimento:");

        TxtDataNascimento.setName("EdtDataNascimento"); // NOI18N
        TxtDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDataNascimentoKeyPressed(evt);
            }
        });

        jLabel9.setText("Código:");

        CbxSituacao.setText("Inativo");
        CbxSituacao.setName("CbxPessoaAtivo"); // NOI18N

        jLabel11.setText("RG:");

        TxtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEstadoKeyReleased(evt);
            }
        });

        jLabel12.setText("Estado:");

        TxtObservacao.setColumns(20);
        TxtObservacao.setRows(5);
        TxtObservacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtObservacaoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TxtObservacao);

        jLabel13.setText("Observação:");

        TxtRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRGKeyPressed(evt);
            }
        });

        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        BtnExcluir.setText("Excluir");
        BtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnExcluirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRetornar)
                        .addGap(43, 43, 43)
                        .addComponent(BtnSalvar))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TxtEstado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TxtRG))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(25, 25, 25))
                                    .addComponent(TxtDataNascimento)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbxSituacao)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(TxtNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TxtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel1)
                        .addComponent(CbxSituacao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRetornar)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnExcluir))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalvarMouseClicked
        // TODO add your handling code here:
        cliente.setNome(TxtNome.getText());
        cliente.setCpf(TxtCPF.getText());
        cliente.setRg(TxtRG.getText());
        cliente.setSituacao(CbxSituacao.isSelected());
        cliente.setCidade(TxtCidade.getText());
        cliente.setEstado(TxtEstado.getText());
        cliente.setEndereco(TxtEndereco.getText());
        cliente.setEnderecoBairro(TxtBairro.getText());
        //cliente.setNumeroEndereco(Integer.parseInt(TxtNumero.getText()));;
        //cliente.setCep(Integer.parseInt(TxtCEP.getText()));
        cliente.setObservacao(TxtObservacao.getText());
        service.SalvarEdiarCliente(cliente);
        JOptionPane.showMessageDialog(this, cliente.getNome() + " cadastrado com sucesso!");
        //Fecha o cadastro do cliente
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_BtnSalvarMouseClicked

    private void BtnRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetornarMouseClicked
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(this, "Deseja Cancelar a Operação", "Confirmação", JOptionPane.YES_NO_OPTION)) {
            case JOptionPane.YES_OPTION:
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_BtnRetornarMouseClicked

    private void TxtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtCPF.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtNomeKeyPressed

    private void TxtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCPFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtRG.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtCPFKeyPressed

    private void TxtDataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDataNascimentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtCEP.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtDataNascimentoKeyPressed

    private void TxtCEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCEPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtEstado.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtCEPKeyPressed

    private void TxtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEstadoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtCidade.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtEstadoKeyReleased

    private void TxtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtEndereco.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtCidadeKeyPressed

    private void TxtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEnderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtBairro.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtEnderecoKeyPressed

    private void TxtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBairroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtNumero.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtBairroKeyPressed

    private void TxtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumeroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtObservacao.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtNumeroKeyPressed

    private void TxtObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtObservacaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnSalvar.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtObservacaoKeyPressed

    private void BtnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSalvarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cliente.setNome(TxtNome.getText());
            cliente.setCpf(TxtCPF.getText());
            cliente.setRg(TxtRG.getText());
            cliente.setSituacao(CbxSituacao.isSelected());
            service.SalvarEdiarCliente(cliente);

            // Após cadastrar, exibe a mensagem de sucesso
            JOptionPane.showMessageDialog(this, cliente.getNome() + " cadastrado com sucesso!");

            //Fecha o cadastro do cliente
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dispose();
        }
    }//GEN-LAST:event_BtnSalvarKeyPressed

    private void TxtRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRGKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TxtDataNascimento.requestFocusInWindow();
        }
    }//GEN-LAST:event_TxtRGKeyPressed

    private void BtnExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExcluirMousePressed
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(this, "Deseja Excluir: " + cliente.getId()
                + ", " + cliente.getNome(), "Confirmação!", JOptionPane.YES_NO_OPTION)) {
            case JOptionPane.YES_OPTION:
                ClienteService service = new ClienteService();
                service.DeletarCliente(cliente.getId());
                JOptionPane.showMessageDialog(null, cliente.getId() + ", " + cliente.getNome() + " Excluido!");

                //Fecha o cadastro do cliente
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_BtnExcluirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JCheckBox CbxSituacao;
    private javax.swing.JLabel LblCodigoCliente;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtCEP;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtDataNascimento;
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextArea TxtObservacao;
    private javax.swing.JTextField TxtRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
