/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema;

import entidades.Produto;
import entidades.ProdutoService;
import entidades.Usuario;
import entidades.UsuarioService;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        abrirTelaCheia();
    }

    private void abrirTelaCheia() {

        // Configura o título da janela
        setTitle("Gerencial");

        // Obtém o tamanho da tela
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        // Define o tamanho da janela para o tamanho da tela
        setSize(screenSize.width, screenSize.height);

        // Define a janela como maximizada
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // Mostra a janela
        setVisible(true);

        //Fechar apenar este formulario
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void fecharAbaClientes() {
        int tabCount = PainelAbas.getTabCount();

        for (int i = 0; i < tabCount; i++) {
            if (PainelAbas.getTitleAt(i).equals("Clientes")) {
                PainelAbas.remove(i); // Fecha a aba se o título for "Clientes"
                break;
            }
        }
    }

    private JPanel criarCabecalhoComBotaoFechar(String titulo) {
        // Cria um painel para o cabeçalho da aba
        JPanel cabecalho = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        cabecalho.setOpaque(false); // Deixa o painel transparente para combinar com o visual da aba

        // Adiciona um rótulo com o título da aba
        JLabel labelTitulo = new JLabel(titulo);
        cabecalho.add(labelTitulo);

        // Cria um botão de fechar "x"
        JButton botaoFechar = new JButton("x");
        botaoFechar.setMargin(new Insets(0, 0, 0, 0));
        botaoFechar.setPreferredSize(new Dimension(17, 17));

        // Adiciona uma ação ao botão para fechar a aba ao clicar
        botaoFechar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Encontra o índice da aba associada a este cabeçalho
                int index = PainelAbas.indexOfTabComponent(cabecalho);
                if (index != -1) {
                    PainelAbas.remove(index);
                }
            }
        });
        // Adiciona o botão de fechar ao cabeçalho
        cabecalho.add(botaoFechar);

        return cabecalho;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAbas = new javax.swing.JTabbedPane();
        TabPnlHome = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BtnListagemDeClientes = new javax.swing.JButton();
        BtnListagemProdutos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        MnCadastros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnClientes = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TabPnlHome.setToolTipText("");
        TabPnlHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PainelAbas.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/icon/house.png")), TabPnlHome, ""); // NOI18N

        BtnListagemDeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/group.png"))); // NOI18N
        BtnListagemDeClientes.setText("cliente");
        BtnListagemDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListagemDeClientesMouseClicked(evt);
            }
        });

        BtnListagemProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cart.png"))); // NOI18N
        BtnListagemProdutos.setText("produto");
        BtnListagemProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListagemProdutosMouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jButton3.setText("usuario");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BtnListagemDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnListagemProdutos)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnListagemProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnListagemDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        MnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/page_add.png"))); // NOI18N
        MnCadastros.setText("Cadastro");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jMenuItem1.setText("Usuários");
        MnCadastros.add(jMenuItem1);

        MnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/group.png"))); // NOI18N
        MnClientes.setText("Clientes");
        MnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnClientesMouseClicked(evt);
            }
        });
        MnCadastros.add(MnClientes);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cart.png"))); // NOI18N
        jMenuItem3.setText("Produtos");
        MnCadastros.add(jMenuItem3);

        jMenuBar2.add(MnCadastros);

        MnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/door_in.png"))); // NOI18N
        MnSair.setText("Sair");
        MnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnSairMouseClicked(evt);
            }
        });
        jMenuBar2.add(MnSair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelAbas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListagemProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListagemProdutosMouseClicked
        // TODO add your handling code here:
        // Verifica se já existe uma aba para "ListagemClientes" antes de adicionar
        boolean existe = false;
        int tabCount = PainelAbas.getTabCount();

        for (int i = 0; i < tabCount; i++) {
            if (PainelAbas.getTitleAt(i).equals("Produtos")) {
                existe = true;
                PainelAbas.setSelectedIndex(i); // Seleciona a aba existente
                break;
            }
        }

        if (!existe) {
            // Cria um novo painel com o formulário de clientes
            ListagemDeProdutos listagemDeProdutos = new ListagemDeProdutos();
            PainelAbas.addTab("Produtos", listagemDeProdutos);
            int index = PainelAbas.indexOfComponent(listagemDeProdutos);
            PainelAbas.setTabComponentAt(index, criarCabecalhoComBotaoFechar("Produtos"));
            PainelAbas.setSelectedComponent(listagemDeProdutos);
        }

    }//GEN-LAST:event_BtnListagemProdutosMouseClicked

    private void BtnListagemDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListagemDeClientesMouseClicked
        // TODO add your handling code here:
        boolean existe = false;
        int tabCount = PainelAbas.getTabCount();

        for (int i = 0; i < tabCount; i++) {
            if (PainelAbas.getTitleAt(i).equals("Clientes")) {
                existe = true;
                PainelAbas.setSelectedIndex(i);
                break;
            }
        }
        if (!existe) {
            ListagemDeClientes listagemDeClientes = new ListagemDeClientes();
            PainelAbas.addTab("Clientes", listagemDeClientes);
            int index = PainelAbas.indexOfComponent(listagemDeClientes);
            PainelAbas.setTabComponentAt(index, criarCabecalhoComBotaoFechar("Clientes"));
            PainelAbas.setSelectedComponent(listagemDeClientes);

        }
    }//GEN-LAST:event_BtnListagemDeClientesMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        UsuarioService service = new UsuarioService();
        Usuario usuario = new Usuario();
        usuario.setNome("Arthur");
        usuario.setLogin("Arthur");
        usuario.setSenha("123");
        usuario.setSituacao(true);
        service.SalvarUsuario(usuario);
    }//GEN-LAST:event_jButton3MouseClicked

    private void MnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnSairMouseClicked
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(this, "Deseja Fechar o Sistema", "Confirmação", JOptionPane.YES_NO_OPTION)) {
            case JOptionPane.YES_OPTION:
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                throw new AssertionError();
        }

    }//GEN-LAST:event_MnSairMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        switch (JOptionPane.showConfirmDialog(this, "Deseja Fechar o Sistema", "Confirmação", JOptionPane.YES_NO_OPTION)) {
            case JOptionPane.YES_OPTION:
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_formWindowClosing

    private void MnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnClientesMouseClicked
        // TODO add your handling code here:

        // Verifica se já existe uma aba para "ListagemClientes" antes de adicionar
        boolean existe = false;
        int tabCount = PainelAbas.getTabCount();

        for (int i = 0; i < tabCount; i++) {
            if (PainelAbas.getTitleAt(i).equals("Clientes")) {
                existe = true;
                PainelAbas.setSelectedIndex(i); // Seleciona a aba existente
                break;
            }
        }

        if (!existe) {
            // Cria um novo painel com o formulário de clientes
            ListagemDeClientes listagemClientes = new ListagemDeClientes();
            PainelAbas.addTab("Clientes", listagemClientes); // Adiciona a aba com o formulário
            PainelAbas.setSelectedComponent(listagemClientes); // Seleciona a nova aba
        }
    }//GEN-LAST:event_MnClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListagemDeClientes;
    private javax.swing.JButton BtnListagemProdutos;
    private javax.swing.JMenu MnCadastros;
    private javax.swing.JMenuItem MnClientes;
    private javax.swing.JMenu MnSair;
    private javax.swing.JTabbedPane PainelAbas;
    private javax.swing.JTabbedPane TabPnlHome;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
